version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-newsletter-command: &newsletter-cmd
  entrypoint: ["node_modules/.bin/basecms-newsletters"]
  command: ["dev", "index.js"]

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-gemenon: &env-gemenon
  GRAPHQL_URI: ${GRAPHQL_URI-https://gemenon.graphql.base-cms.io}

x-env-picon: &env-picon
  GRAPHQL_URI: ${GRAPHQL_URI-https://picon.graphql.base-cms.io}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  ecmweb:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/ecmweb
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19400
      LIVERELOAD_PORT: 29400
      TENANT_KEY: ebm_ecmweb
    ports:
      - "19400:80"
      - "29400:29400"

  tdworld:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/tdworld
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19401
      LIVERELOAD_PORT: 29401
      TENANT_KEY: ebm_tdworld
    ports:
      - "19401:80"
      - "29401:29401"

  ewweb:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/ewweb
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19402
      LIVERELOAD_PORT: 29402
      TENANT_KEY: ebm_ewweb
    ports:
      - "19402:80"
      - "29402:29402"

  rermag:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/rermag
    environment:
      <<: *env
      <<: *env-gemenon
      PORT: 80
      EXPOSED_PORT: 19403
      LIVERELOAD_PORT: 29403
      TENANT_KEY: ebm_rermag
    ports:
      - "19403:80"
      - "29403:29403"

  vspc:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/vspc
    environment:
      <<: *env
      <<: *env-picon
      PORT: 80
      EXPOSED_PORT: 19404
      LIVERELOAD_PORT: 29404
      TENANT_KEY: cygnus_vspc
    ports:
      - "19404:80"
      - "29404:29404"

volumes:
  yarn-cache: {}
